### ISSUE TITLE
Inference Code and Checkpoints Release date for VideoTetris?

### ISSUE THREAD

**Issue by ninjasaid2k** [YangLing0818/VideoTetris#1]
I appreciate the work on VideoTetris presented in your paper. I am requesting to know if you have a release window to release the checkpoints or code thank you.

**Comment by YangLing0818** [comment]
> I appreciate the work on VideoTetris presented in your paper. I am requesting to know if you have a release window to release the checkpoints or code thank you.

Thanks for your attention. We may release the code and checkpoint within one month

**Comment by shiverwang76** [comment]
> > I appreciate the work on VideoTetris presented in your paper. I am requesting to know if you have a release window to release the checkpoints or code thank you.
> 
> Thanks for your attention. We may release the code and checkpoint within one month

What hardware does open source code need to train videos?
