### ISSUE TITLE
StreamingT2V training code

### ISSUE THREAD

**Issue by o0o0o00o0** [YangLing0818/VideoTetris#6]
I really appreciate your great work! In your paper, you said that you fine-tuned streamingT2V with the newly extracted dataset. Can you share the training code of streamingT2V, as streamingT2V itself has not yet made its training code public? Thank you very much!

**Comment by tyfeld** [comment]
Hi, I have made made it public months ago, please refer to https://github.com/tyfeld/train-StreamingT2V.

**Comment by o0o0o00o0** [comment]
> Hi, I have made made it public months ago, please refer to https://github.com/tyfeld/train-StreamingT2V.

Thank you so much!
